### ISSUE TITLE
Build HTML on readthedocs.org

### ISSUE THREAD

**Issue by yungyuc** [yungyuc/cmdpower#2]
Set up a corresponding project on https://readthedocs.org to build the `master` branch.

**Comment by YenPeiChen07** [comment]
@yungyuc I have created a project on [https://readthedocs.org/]( https://readthedocs.org/) by importing the doc. 

Here is the URL for the doc: [cmdpower.readthedocs.io](https://cmdpower.readthedocs.io/zh_TW/latest/)

**Comment by yungyuc** [comment]
LGTM.  Thanks.
